# Generated by Django 5.1.3 on 2024-12-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='filePath',
        ),
    ]
