# Generated by Django 5.1.3 on 2024-12-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_image_project_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='websiteURL',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
